<p><img alt="Colaboratory logo" height="200px" src="https://i.ibb.co/WkGZKhF/book.png" align="left" hspace="10px" vspace="0px"></p>

## Table of Contents:
* [Matrix Addition](#add)
* [Matrix Subtraction](#sub)
* [Matrix Multiplication](#mult)
* [Matrix Division](#div)
* [Transpose of a Matrix](#tra)
* [Inverse of a Matrix](#tra)
* [Trace of a Matrix](#trac)
* [Determinant of a Matrix](#det)
* [Eigenvector and Eigenvalue](#eig)
* [Deep Learning](#dee)


In [33]:
import numpy as np

<a href="https://imgbb.com/"><img src="https://i.ibb.co/8mxZyhw/mat.png" alt="mat" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>

<a name="add"></a>
Matrix addition

In [34]:
A = np.array([[1, 2], 
              [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [35]:
B = np.array([[5, 6], 
              [7, 8]])
print(B)

[[5 6]
 [7 8]]


In [36]:
A + B

array([[ 6,  8],
       [10, 12]])

<a name="sub"></a>
Matrix subtraction

In [37]:
A-B

array([[-4, -4],
       [-4, -4]])

<a name="mult"></a>
Matrix Multiplication (Hadamard Product)






In [38]:
A*B

array([[ 5, 12],
       [21, 32]])

Matrix Multiplication (Dot Product)


In [39]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

<a name="div"></a>
Matrix Division


In [40]:
A/B

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

<a name="tra"></a>
<a href="https://ibb.co/23t4PHD"><img src="https://i.ibb.co/CK7GvDk/trans.png" alt="trans" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>

In [41]:
M = np.array([[1, 2], 
              [3, 4],
              [5, 6]])
print(M)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
M.T

array([[1, 3, 5],
       [2, 4, 6]])

<a name="inv"></a>
<a href="https://ibb.co/2hFYFxk"><img src="https://i.ibb.co/Gpd3dy5/inv.png" alt="inv" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>

In [43]:
A

array([[1, 2],
       [3, 4]])

In [44]:
IN = np.linalg.inv(A)

In [45]:
IN

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [46]:
np.matmul(A,IN).round()

array([[1., 0.],
       [0., 1.]])

<a name="trac"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/56WW0zh/trac.png" alt="trac" border="0"></a>

In [47]:
np.matrix.trace(A)

5

<a name="det"></a>
<a href="https://ibb.co/Hzfn2Nn"><img src="https://i.ibb.co/ncNz03z/det.png" alt="det" border="0"></a>

In [48]:
np.linalg.det(A)

-2.0000000000000004

<a name="eig"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/7tjnLNZ/decomp.png" alt="decomp" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>

In [49]:
eigenvalue, eigenvector = np.linalg.eig(A)
print("Eigenvalue :",eigenvalue)
print("Eigenvector :",eigenvector)

Eigenvalue : [-0.37228132  5.37228132]
Eigenvector : [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


<a name="dee"></a>
<a href="https://ibb.co/ZSrrXrX"><img src="https://i.ibb.co/Scggygy/ann.png" alt="ann" border="0"></a>

In [50]:
import tensorflow as tf

In [51]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [52]:
import pandas as pd
data = pd.read_csv("/content/drive/My Drive/ann_used_cars.csv", usecols=["mileage", 'year'], nrows=4)
data

mileage  year
0     7413  2011
1    10926  2011
2     7351  2011
3    11613  2011

<a href="https://ibb.co/w05LTnD"><img src="https://i.ibb.co/0DHXk0P/matmul.png" alt="matmul" border="0"></a>

In [53]:
features=tf.convert_to_tensor(data, dtype= tf.float32)
features

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 7413.,  2011.],
       [10926.,  2011.],
       [ 7351.,  2011.],
       [11613.,  2011.]], dtype=float32)>

In [54]:
weights = tf.constant([2,.5], shape=[2,1])
weights

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2. ],
       [0.5]], dtype=float32)>

In [55]:
featuresXweights = tf.matmul(features, weights)
featuresXweights

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[15831.5],
       [22857.5],
       [15707.5],
       [24231.5]], dtype=float32)>

Vector + scaler

<a href="https://ibb.co/LrGgHJq"><img src="https://i.ibb.co/ScLmGd1/scaler.png" alt="scaler" border="0"></a>

In [56]:
featuresXweights + 7

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[15838.5],
       [22864.5],
       [15714.5],
       [24238.5]], dtype=float32)>